# Required
- name: Install epel-release
  yum: state=latest name=epel-release

- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - policycoreutils-python
    - firewalld
    - curl
    - wget
    - screen
    - lsof
    - jq
    - pv

- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-edge'
    option: enabled
    value: '{{ docker_yum_repo_enable_edge }}'

- name: Configure Docker Test repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-test'
    option: enabled
    value: '{{ docker_yum_repo_enable_test }}'
